// packages/draggable/playgrounds/dflex-react-draggable/src/components/Container.jsx
/* eslint-disable no-use-before-define */
import React from "react";

import { Draggable } from "@dflex/draggable/src";

const Container = ({
  component: ContainerComponent = "div",
  children,
  ...rest
}) => {
  let mouseEvents;

  let draggable;

  let draggedID = null;

  const onMouseDown = (e) => {
    const { target, button, clientX, clientY } = e;

    // avoid right mouse click and ensure id
    if (typeof button === "number" && button === 0) {
      const { id } = target;

      if (id) {
        draggedID = id;

        draggable = new Draggable(id, { x: clientX, y: clientY });

        mouseEvents = [
          { evType: "mousemove", evTarget: document, handler: onMouseMove },
          { evType: "mouseup", evTarget: document, handler: onMouseUp },
        ];

        mouseEvents.forEach(({ evType, evTarget, handler }) => {
          evTarget.addEventListener(evType, handler);
        });
      }
    }
  };

  const onMouseUp = () => {
    if (draggedID) {
      mouseEvents.forEach(({ evType, evTarget, handler }) => {
        evTarget.removeEventListener(evType, handler);
      });

      draggable.endDragging();
    }
  };

  const onMouseMove = (e) => {
    const { clientX, clientY } = e;

    draggable.dragAt(clientX, clientY);
  };

  return (
    <ContainerComponent onMouseDown={onMouseDown} {...rest}>
      {children}
    </ContainerComponent>
  );
};

export default Container;

// packages/draggable/playgrounds/dflex-vue-draggable/src/components/Container.vue
<template>
  <div @mousedown.prevent="onMouseDown"  class="Container">
    <Drag :id="generateKey()">
      <Core v-for="n in [1]"
        :key="'left-' + n"
        :id="generateKey()"
        :content="'Hello-' + n"
        />
    </Drag>
    <Drag :id="generateKey()">
      <Core v-for="n in [1, 2, 3, 4, 5, 6, 7]"
        :key="'center-' + n"
        :id="generateKey()"
        :content="'Hello-' + n"
        />
    </Drag>
    <Drag :id="generateKey()">
      <Core v-for="n in [1, 2, 3]"
        :key="'right-' + n"
        :id="generateKey()"
        :content="'Hello-' + n"
        />
    </Drag>
  </div>
</template>

<script>
// Import dependencies
import { Draggable } from "@dflex/draggable/src";
import { keyGenerator } from "@folo/utils"
// Import components
import Drag from './Drag.vue'
import Core from './Core.vue'

export default {
  name: 'Container',

  components: {
    Core,
    Drag
  },

  data: function () {
    return { 
      id: keyGenerator(new Date().getTime()),
      mouseEvents: null,
      draggable: null,
      draggedID: null 
    }
  },

  methods: {
    generateKey: function () {
      return keyGenerator(new Date().getTime().toString())
    },

    onMouseDown: function(e)  {
      const { target, button, clientX, clientY } = e;
      // avoid right mouse click and ensure id
      if (typeof button === "number" && button === 0) {
        const { id } = target;
        if (id) {
          this.draggedID = id;
          this.draggable = new Draggable(id, { x: clientX, y: clientY });
          this.mouseEvents = [
            { evType: "mousemove", evTarget: document, handler: this.onMouseMove },
            { evType: "mouseup", evTarget: document, handler: this.onMouseUp },
          ];
          this.mouseEvents.forEach(({ evType, evTarget, handler }) => {
            evTarget.addEventListener(evType, handler);
          });
        }
      }
    },

    onMouseUp: function() {
      if (this.draggedID) {
        this.mouseEvents.forEach(({ evType, evTarget, handler }) => {
          evTarget.removeEventListener(evType, handler);
        });
        this.draggable.endDragging();
      }
    },

    onMouseMove: function(e) {
      if(this.draggedID) {
        const { clientX, clientY } = e;
        this.draggable.dragAt(clientX, clientY);
      }
    }
  }
}
</script>

<style scoped>
.Container {
  display: flex;
  width: 41.53rem;
  /* border: 4px green solid; */
  background: #07718f;
}
</style>
